Import('*')

figures = []

source = [
    '#source/paper/inflation_expectations.lyx',
    '#source/paper/inflation_expectations.bib'
] + figures

target = [
    '#output/paper/inflation_expectations.pdf'
]

env.Lyx(target, source)



